### ISSUE TITLE
Could not find the function sparse_update_inplace

### ISSUE THREAD

**Issue by douzeyang** [zhouyuanzxcv/Hyperspectral#1]
Hi,
    Nice work! When I tried to run the GMM demo test_gmm.m, the matlab showed me that it cannot find the sparse_update_inplace function. Could you please fix this?

**Comment by zhouyuanzxcv** [comment]
Thanks for pointing it out. It is because the "common" folder is not included in the path. I changed the "test_gmm.m" file to include it.

**Comment by douzeyang** [comment]
> Thanks for pointing it out. It is because the "common" folder is not included in the path. I changed the "test_gmm.m" file to include it.

Thanks for your check. However, the matlab still showed me the massage of the missing function. I realized that it is the problem of the platform, because I used matlab on Ubuntu 16.04, while the sparse_update_inplace function is the mexw64 file which is for Windows. I will change the operation system. Anyway, thanks!
